config/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)  # what include?  urls.py(in core)에 작성한 urlpatterns를 url.config에 넣어주기 위해 필요

# settings 를 import 하고 싶을때, not from . import settings! (장고는 프레임 워크라는 사실을 잊지말귕.)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ""는 / 를 의미한다
    path(
        "", include("core.urls", namespace="core")
    ),  # what include?  urls.py(in core)에 작성한 urlpatterns를 url.config에 넣어주기 위해 필요
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# static 과 URL("/media/")을 폴더(os.path.join(BASE_DIR,"uploads"))에 연결하기
if settings.DEBUG:  # ==내가 개발중이라면(프로덕션이 아니라면)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )  # (#8.4) static? > 장고헬퍼. static 파일들을 제공하는 것을 도움
    # /media/ 폴더를 제공하고 싶다고 static 에게 말한다. URL/media 는 media_root 안으로 들어갈 것이다.
    # 이 뒤로 사진 클릭 시, http://127.0.0.1:8000/media/room-photos/ooo.jpg를 가지게 되는 것을 확인가능
"""
# 장고에게 어떻게 폴더안의 파일들을 제공하는지 ?
# 다시말해, 내가 Amazon 같은 곳에 장고를 업로드 할 때, 어떻게 내가 파일들을 서버 폴더에 저장하지 않을 것인지 ? 를 가르쳐주겠대
# ***마지막 챕터에서 가르쳐 준대!!!!!!! 왜냐면 난 하나의 서버만을 가질 때가 있을 텐데, 그건 많은 트래픽이 발생갈 것이고 , 그래서 난 엄청 서버 코드를 복제하겠지? 그치만
# 서버 코드에서는 사용자 파일들을 저장하고 싶지 않을 거야. 그래서 Amazon s3 같은 것을 사용하는 것이고..얘는 내 파일들을 서버에 업로드 하게 해주거든
# 그래서 내가 백개의 서버를 가지던, 하개를 가지던 서버가 없건 전혀 문제 될 게 없어.
# 왜냐면 사용자가 업로드할 파일들이 Amazon s3 의 다른 저장소에 저장될테니까. 떄문에 개발할 마지막 챕터때, 작업이 이루어 질 거라 하셨다!
"""

core/urls.py
"""
프로젝트를 하다보면 엄청난 양의 url 이 발생하기때문에 이를 위해 divide and conquer 이 필요하다
다시말해, /rooms 로 시작하는 url 들은 room 파일로 가게하고,
/users 로 시작한다면 그것은 user 파일로 가게하는데,
아무것으로도 시작하지않는, 예를 들면 /home, /login, /logout 같은 것들은 바로 여기, core 로 가게 한다.
장고안의 어플리케이션들은 기본으로 urls.py(in config) 로 오지 않는다. 만들어야됨..!
"""

from django.urls import path
from rooms import views as room_views

app_name = "core"  # 이 "core" 와 config.urls 의 namespace 랑 이름이 깉아야한다.

urlpatterns = [
    path(  # as_view 메소드 ? HomeView자체는 class 이므로 path는 오로지 url 혹은 함수만을 갖기 때문에 이 메소드를 통해 class 를 view로 변경해준다.
        "", room_views.HomeView.as_view(), name="home"  # view 에 home 이라는 이름을 주었음
    ),  # 이렇게 하고, urls.py(in config) 가서 path를 include 해주는 작업만 해주면 된다.
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

# 아래와 같이 선언 후, config 폴더 안(core아님) urls.py에 추가해주도록 하는 거 잊지마릭
urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
]

templates/partials/footer.html
<footer>
    <!--카피라이트 기호 삽입-->
    &copy; YeonJubnb
</footer>

templates/partials/navigation.html
<a href="{% url "core:home" %}">YeonJubnb</a>
<ul>
    <!-- is_authenticated ? user 가 이미 인증되어있는지 확인. (#14.4))
        그런데 여기서 , 궁금증이 생김. user는 어디서 나타났고 어떻게 이 navigation 파일이 user 에 access 할 수 있을까?
        장고는 Context Processor 함수 라는걸 가지고 있음. (#14.4) 이건 나의 template 에 정보를 추가하는 일을 하는데, 어디서든 그 template 으로 접근할 수 있다.
        (그 뷰의 Context 가 아닌 어디서든 접근 할 수 있음.) 아래 같은 경우에서는 ,
        Context Processor 가 쿠키를 가져와서 user을 찾고, 그걸 template 에 자동으로 넣어주는 것임.
    -->
    {% if user.is_authenticated  %}
    <li><a href="{% url "users:logout" %}">Log out </a></li>
    {% else %}
    <li><a href="{% url "users:login" %}">Login </a></li>
    <li><a href="{% url "users:signup" %}"> Sign Up</a></li>
    {% endif %}


</ul>