config/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)  # what include?  urls.py(in core)에 작성한 urlpatterns를 url.config에 넣어주기 위해 필요

# settings 를 import 하고 싶을때, not from . import settings! (장고는 프레임 워크라는 사실을 잊지말귕.)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ""는 / 를 의미한다
    path(
        "", include("core.urls", namespace="core")
    ),  # what include?  urls.py(in core)에 작성한 urlpatterns를 url.config에 넣어주기 위해 필요
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# static 과 URL("/media/")을 폴더(os.path.join(BASE_DIR,"uploads"))에 연결하기
if settings.DEBUG:  # ==내가 개발중이라면(프로덕션이 아니라면)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )  # (#8.4) static? > 장고헬퍼. static 파일들을 제공하는 것을 도움
    # /media/ 폴더를 제공하고 싶다고 static 에게 말한다. URL/media 는 media_root 안으로 들어갈 것이다.
    # 이 뒤로 사진 클릭 시, http://127.0.0.1:8000/media/room-photos/ooo.jpg를 가지게 되는 것을 확인가능
"""
# 장고에게 어떻게 폴더안의 파일들을 제공하는지 ?
# 다시말해, 내가 Amazon 같은 곳에 장고를 업로드 할 때, 어떻게 내가 파일들을 서버 폴더에 저장하지 않을 것인지 ? 를 가르쳐주겠대
# ***마지막 챕터에서 가르쳐 준대!!!!!!! 왜냐면 난 하나의 서버만을 가질 때가 있을 텐데, 그건 많은 트래픽이 발생갈 것이고 , 그래서 난 엄청 서버 코드를 복제하겠지? 그치만
# 서버 코드에서는 사용자 파일들을 저장하고 싶지 않을 거야. 그래서 Amazon s3 같은 것을 사용하는 것이고..얘는 내 파일들을 서버에 업로드 하게 해주거든
# 그래서 내가 백개의 서버를 가지던, 하개를 가지던 서버가 없건 전혀 문제 될 게 없어.
# 왜냐면 사용자가 업로드할 파일들이 Amazon s3 의 다른 저장소에 저장될테니까. 떄문에 개발할 마지막 챕터때, 작업이 이루어 질 거라 하셨다!
"""

core/urls.py
"""
프로젝트를 하다보면 엄청난 양의 url 이 발생하기때문에 이를 위해 divide and conquer 이 필요하다
다시말해, /rooms 로 시작하는 url 들은 room 파일로 가게하고,
/users 로 시작한다면 그것은 user 파일로 가게하는데,
아무것으로도 시작하지않는, 예를 들면 /home, /login, /logout 같은 것들은 바로 여기, core 로 가게 한다.
장고안의 어플리케이션들은 기본으로 urls.py(in config) 로 오지 않는다. 만들어야됨..!
"""

from django.urls import path
from rooms import views as room_views

app_name = "core"  # 이 "core" 와 config.urls 의 namespace 랑 이름이 깉아야한다.

urlpatterns = [
    path(  # as_view 메소드 ? HomeView자체는 class 이므로 path는 오로지 url 혹은 함수만을 갖기 때문에 이 메소드를 통해 class 를 view로 변경해준다.
        "", room_views.HomeView.as_view(), name="home"  # view 에 home 이라는 이름을 주었음
    ),  # 이렇게 하고, urls.py(in config) 가서 path를 include 해주는 작업만 해주면 된다.
]

rooms/urls.py
# detail.html 을 위해 생성한 파일.
# detail.html 은 core 내의 url 이 필요 없기에 ,room 앱 안에서 url을 만들어 주었다.

from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path(  # 이 path도 선언 후 config 안의 url파일 내에 import 해주어야만 한다.
        "<int:pk>", views.RoomDetail.as_view(), name="detail"
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from core import models as core_models
from users import models as user_models


class AbstractItem(core_models.TimeStampedModel):  # RoomType 을 만들기위해 생성한 class
    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ["created"]


class Amenity(AbstractItem):
    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Photo(
    core_models.TimeStampedModel
):  # 아래 코드 중, Foreign 키로 Room이 연결되어 줘야 하므로 위에있으면 파이썬이 Room 을 못찾음. Room class 아래에 이 photo클래스 선언해주어야함.
    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(
        upload_to="room-photos"  # upload_to? 장고야, uploads 폴더 안의 room-photos 폴더에 사진을 업로드 해줘!(폴더 없으면 너가 생성해!)
    )  # room 은 photo 와 연결이 되어야 하므로 이를 연결시켜줌 (그리고 room 은 user 와 연결됨)
    room = models.ForeignKey(
        "Room", related_name="photos", on_delete=models.CASCADE
    )  # 사진을 지우면 room도 연결되어있기 떄문에 함께 지워져야 함

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """Room Model Definition"""

    name = models.CharField(max_length=140, blank=True)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User",
        related_name="rooms",  # (= user가 어떻게 우리를 찾기를 원합니까?) room__set 대신 rooms 이라 쳐서 찾길 원해! >> 터미널에서, 변수.room.all()으로 검색할수 있게됨!
        # 결국, "room" 이 set 이 된 것 이다!
        on_delete=models.CASCADE,  # host 필드가 user 과 연결이 되있는 결과를 확인할 수 있음!
    )  # host 는 결국 user 인 셈이기 떄문에, user 모델과 이 모델을 연결해서 쓰면 되는 것임. so, import user
    # cascade 는 내가 user 을 삭제했을 때, room 도 삭제하고자 하기 위함이다.
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField(
        "Amenity", related_name="rooms", blank=True
    )  # Manytomany 는 다대다 관계
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rule = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)  # 사용자가 소문자로 입력시 첫 글자 대문자로 바꿔주기 위함
        super().save()

    def total_rating(self):  # room 에서 review 의 모든 리뷰들을 가져와서 평균을 얻기 위한 함수.
        # 이 함수도 왜 admin에 안쓰고 model에 써준거냐? reviwq 패널 외의 다른 곳에도 그 평균 제공 기능이 존재하기때문
        all_reviews = (
            self.reviews.all()
        )  # class Riview 가보면, room 을 가지고 있음. 그리고 그 룸은 related_name= "reviews"를가짐
        # 그 말은, room 이 reviews 를 가진다는 것

        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews))  # 반올림
        return 0

    def get_absolute_url(self):

        return reverse("rooms:detail", kwargs={"pk": self.pk})

rooms/forms.py
from django import forms
from . import models
from django_countries.fields import CountryField


class SearchForm(forms.Form):

    city = forms.CharField(initial="Any")
    country = CountryField(default="KR").formfield()
    price = forms.IntegerField(required=False)
    # <select>대신 사용하는 ModelChoiceField 는 쿼리셋을 필요로 하기 때문에 다음과 같이 쓴다.
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)

    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    # <input type=checkbox> 대신 사용하는 ModelMultipleChoiceField 도 쿼리셋을 필요로 하므로 다음과 같이 작성한다.
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
# RoomView 로 우린 Listview class 가 필요하기에 이를 import 해준다.
from django.views.generic import ListView, DetailView, View

# from django.http import Http404
# from django.urls import reverse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django_countries import countries
from . import models, forms

# 11.6 까지 했던 모든 paginator 와 try-except 로 예외 처리했던 모든 부분을 지우고 아래와같이 Homeview라 선언한 class based view로 다시 시작해보자.
# 추가적으로 core 폴더의 urls.py 내 urlpatterns 도 바뀐 것에 맞게 room_views.HomeView 로  수정해주어야 겠지.
class HomeView(ListView):
    """ HomeView Definition """

    model = models.Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    # 아래와 같이 작성하면서, room_list.html에서는 object_list 대신 rooms라 써서 object 불러옴
    context_object_name = "rooms"


class RoomDetail(DetailView):
    """ RoomDetail Definition """

    model = models.Room


"""
def room_detail(request, pk):  # urls 에서 내가 선언한 pk 변수를 인자로 받아서 쓰면 됨
    try:
        # db 에서 room 정보 갖고 오기
        room = models.Room.objects.get(pk=pk)
        return render(request, "rooms/detail.html", {"room": room})
    except models.Room.DoesNotExist:
        # return redirect(reverse("core:home"))  # core:home url을 받아서 redirect 해줄 것임
        # reverse를 url 대신 쓸 수 있도록 연습하자! 엄청 도움이 된다고 한다
        raise Http404()
"""


class SearchView(View):
    """ SearchView Dafinition"""

    def get(self, request):
        country = request.GET.get("country")
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                print(form.cleaned_data)
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                price = form.cleaned_data.get("price")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}
                # city__startswith 의 city 는 models.py 안에서 내가 선언한 변수명을 똑같이 쓴 것. 아래의 조건부도 동일한 방법으로 써야함.
                if city != "Any":
                    filter_args["city__startswith"] = city

                # country 는 default 를 KR 로 해놓았기 때문에, 조건부를 설정할 필요가 없이 그냥 fileter_args에 집어넣어주면 됨.
                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args[
                        "price__lte"
                    ] = price  # price 는 사용자 입장에서 하루 최대 숙박비이므로 __lte 를 활용

                if guests is not None:
                    filter_args[
                        "guests__gte"
                    ] = guests  # geust 같은 경우는 가장 최소 인원으로 선택하게 되니깐 __gte 를 활용

                if bedrooms is not None:
                    filter_args["bedrooms__lte"] = bedrooms

                if beds is not None:
                    filter_args["beds__lte"] = beds

                if baths is not None:
                    filter_args["baths__lte"] = baths

                # instant_book 은 models.py에서 선언했던 변수명으로서 가져온 것임
                if instant_book is not True:
                    filter_args[
                        "instant_book"
                    ] = True  # False 인건 신경 안써도 되니까 그냥 조건부없이 True 해줌

                # super_host 는 models.py 안에 있지 않아. 그러나 FK 를 이용해서 필터링이 가능하다 !!!
                if superhost is not True:
                    # host 는 models.py를 보면, host 의 FK가 user이고 user 내부모델에 superhost 가 있으므로 이런식으로 필터링을 한다는 것임
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                query_set = models.Room.objects.filter(**filter_args).order_by(
                    "-created"
                )
                paginator = Paginator(query_set, 10, orphans=5)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchForm()

        return render(
            request,
            "rooms/search.html",
            {"form": form},
        )

templates/rooms/detail.html
{% extends 'base.html' %}


{% block page_name %}
Home
{% endblock page_name %}


{% block content %}

<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>

<div>
    <h2> By : {{room.host.username}}

        {% if room.host.superhost %}
        (superhost)
        {% endif %}

    </h2>
    <h3>Amenities</h3>
    <ul>
        {% for a in room.amenities.all%}
        <li>{{a}}</li>
        {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>

        {% for f in room.facilities.all  %}
        <li>{{f}}</li>
        {% endfor %}
    </ul>

</div>

{% endblock content %}

templates/rooms/home.html
<!--base.html을 아웃라인으로 사용하기 위해서는 이 파일에 base를 확장시켜주어야 한다.아래와 같이 선언해준다-->
{% extends 'base.html' %}


{% block page_name %}
Home
{% endblock page_name %}


{% block content %}
{% for room in rooms.object_list  %}
<!--object_list 가 paginator 안에 내제되어 바로 사용이 가능-->
<h1>{{room.name}} / ${{room.price}} </h1>
{% endfor %}

<h5>
    <!-- page+1 로 바로 쓰지 못한다. django tag 중 filter tag 안의 add 를 활용한다. -->
    {% if rooms.has_previous %}
    <!--rooms 는 views.py 내의 rooms라 선언한 paginator에서 온 페이지임.-->
    <a href="?page={{rooms.previous_page}}"> Previous </a>
    {% endif %}

    Page {{rooms.number}} of {{rooms.paginator.num_pages}}

    {% if rooms.has_next %}
    <a href="?page={{rooms.next_page_number}} "> Next </a>"
    {% endif %}

</h5>
<!-- for 문안에 range()를 바로 작성하는 것은 지원하지 않으므로 , view.py 안의 context 에 변수로서 전달하여 사용 해야 한다.-->
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %}


{% block page_title %}
{{room.name}}
{% endblock page_title %}


{% block content %}

<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>

<div>
    <h2> By : {{room.host.username}}

        {% if room.host.superhost %}
        (superhost)
        {% endif %}

    </h2>
    <h3>Amenities</h3>
    <ul>
        {% for a in room.amenities.all%}
        <li>{{a}}</li>
        {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>

        {% for f in room.facilities.all  %}
        <li>{{f}}</li>
        {% endfor %}
    </ul>

</div>

{% endblock content %}

templates/rooms/room_list.html
<!--base.html을 아웃라인으로 사용하기 위해서는 이 파일에 base를 확장시켜주어야 한다.아래와 같이 선언해준다-->
{% extends 'base.html' %}


{% block page_title %}
Home
{% endblock page_title %}


{% block content %}
{% for room in rooms  %}
<!--위 rooms는 views.py 내의 context_object_name = "rooms" 로 인해 object_list라고 칭하는 대신 rooms로 불러 오는 것임-->
<!--ListView 가 실행되는 동안 self.object_list는 objects의 목록을 포함하고 있으므로, 우리가 바로 액세스 가능하다. (11.7)-->
<h3>
    <!-- 아래와 같은 url tag 쓰는 법 12.0 필기 참고-->
    <a href="{% url "rooms:detail" room.pk %}">
        {{room.name}} / ${{room.price}}
    </a>
</h3>
{% endfor %}

<h5>
    <!-- page+1 로 바로 쓰지 못한다. django tag 중 filter tag 안의 add 를 활용한다. -->
    {% if page_obj.has_previous %}
    <!--rooms 는 views.py 내의 rooms라 선언한 paginator에서 온 페이지임.-->
    <a href="?page={{page_obj.previous_page}}"> Previous </a>
    {% endif %}

    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

    {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}} "> Next </a>"
    {% endif %}

</h5>
<!-- for 문안에 range()를 바로 작성하는 것은 지원하지 않으므로 , view.py 안의 context 에 변수로서 전달하여 사용 해야 한다.-->
{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
Search
{% endblock page_title %}


{% block search_bar %}

{% endblock search_bar %}


{% block content %}
<h2> Search! </h2>
<form method="get" action="{% url "rooms:search" %}">
    <!-- .as_p : paragraph 형태로 form 출력 해주는 메소드-->
    {{form.as_p}}
    <button> Search</button>
</form>

<h3>Results</h3>

{% for room in rooms  %}
<h3>{{room.name}}</h3>
{% endfor %}



{% endblock content %}